
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: MyApp Deploy
on:
  workflow_call:
    inputs:
      artifactName:
        type: string
        required: true
      artifactVersion:
        type: string
        required: true
      environment:
        type: string
        required: true
      url:
        type: string
        required: false
      digest:
        type: string
        required: false
jobs:
  pre-prod:
    if: inputs.environment == 'pre-prod'
    environment: pre-prod
    steps:
      - name: Inform system that an artifact version was deployed
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "${{ inputs.artifactName }}"
          version: "${{ inputs.artifactVersion }}"
          url: "docker.io/MyApp/${{ inputs.artifactName }}:${{ inputs.artifactVersion }}"
  prod:
    if: inputs.environment == 'prod'
    environment: prod
    steps:
      - name: Inform system that an artifact version was deployed
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          name: "${{ inputs.artifactName }}"
          version: "${{ inputs.artifactVersion }}"
          url: "docker.io/MyApp/${{ inputs.artifactName }}:${{ inputs.artifactVersion }}"
